site_name: "Tableau: Extended Tables"

theme:
  name: material

markdown_extensions:
  - mdx_tableau
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true   
  - pymdownx.arithmatex:
      generic: true

extra_javascript: 
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css: 
  - assets/css/tableau.css
